# Generated by Django 5.1.1 on 2024-12-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
